### ISSUE TITLE
"Program received signal SIGILL, Illegal instruction." on Core 2 Duo

### ISSUE THREAD

**Issue by VVD** [google/highway#560]
FreeBSD 12.3 amd64, Core 2 Duo E7200 and E6550.
```
$ /usr/bin/c++ --version
FreeBSD clang version 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2)
Target: x86_64-unknown-freebsd12.3
Thread model: posix
InstalledDir: /usr/bin
```
Build with clang 13 nothing changed.
```
$ /usr/local/bin/clang++13 --version
clang version 13.0.1
Target: x86_64-portbld-freebsd12.3
Thread model: posix
InstalledDir: /usr/local/llvm13/bin
```

Tested options `-O2 -march=nocona` and `-O2 -march=core2`.

```
$ gdb gdk-pixbuf-query-loaders
GNU gdb (GDB) 11.2 [GDB v11.2 for FreeBSD]
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-portbld-freebsd12.3".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gdk-pixbuf-query-loaders...
(No debugging symbols found in gdk-pixbuf-query-loaders)
(gdb) run
Starting program: /usr/local/bin/gdk-pixbuf-query-loaders
g_module_open() failed for /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-avif.so: /usr/local/lib/libyuv.so: Undefined symbol "jpeg_resync_to_restart"

Program received signal SIGILL, Illegal instruction.
Privileged opcode.
0x0000000800cfd3a2 in ?? () from /usr/local/lib/libhwy.so.0
(gdb) bt -full
#0  0x0000000800cfd3a2 in  () at /usr/local/lib/libhwy.so.0
#1  0x000000080021247d in  () at /libexec/ld-elf.so.1
#2  0x00007fffffffdc00 in  ()
#3  0x0000000800214d05 in  () at /libexec/ld-elf.so.1
#4  0x00007fffffffdc20 in  ()
#5  0x0000000800d5b920 in  () at /usr/local/lib/libbrotlienc.so.1
#6  0x00000008002170a4 in  () at /libexec/ld-elf.so.1
#7  0x000000080022c2f0 in  () at /libexec/ld-elf.so.1
#8  0x0000000800be9800 in  ()
#9  0x00007fffffffe8f0 in  ()
#10 0x0000000800be9000 in  ()
#11 0x00007fffffffdff0 in  ()
#12 0x000000080021a17b in  () at /libexec/ld-elf.so.1
#13 0x0000000000be9801 in  ()
#14 0x0000000800be7ee0 in  ()
#15 0x00007fffffffe480 in  ()
#16 0x0000000800219980 in  () at /libexec/ld-elf.so.1
#17 0x0000000000000000 in  ()
```
```
$ valgrind gdk-pixbuf-query-loaders ==81101== Memcheck, a memory error detector
==81101== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==81101== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==81101== Command: gdk-pixbuf-query-loaders
==81101== 
g_module_open() failed for /usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-avif.so: /usr/local/lib/libyuv.so: Undefined symbol "jpeg_resync_to_restart"
==81101== Warning: set address range perms: large range [0x7ea7000, 0x30236000) (noaccess)
==81101== Warning: set address range perms: large range [0x8236000, 0x30236000) (defined)
==81101== Warning: set address range perms: large range [0x7ea7000, 0x30236000) (noaccess)
vex amd64->IR: unhandled instruction bytes: 0xF 0x1 0xF9 0x48 0xC1 0xE2 0x20 0x48 0x9 0xD0
vex amd64->IR:   REX=0 REX.W=0 REX.R=0 REX.X=0 REX.B=0
vex amd64->IR:   VEX=0 VEX.L=0 VEX.nVVVV=0x0 ESC=0F
vex amd64->IR:   PFX.66=0 PFX.F2=0 PFX.F3=0
==81101== valgrind: Unrecognised instruction at address 0x52bf3a2.
==81101==    at 0x52BF3A2: ??? (in /usr/local/lib/libhwy.so.0.16.0)
==81101==    by 0x400D47C: ??? (in /libexec/ld-elf.so.1)
==81101==    by 0x40120A3: ??? (in /libexec/ld-elf.so.1)
==81101==    by 0x400E79A: ??? (in /libexec/ld-elf.so.1)
==81101==    by 0x49F6B3B: g_module_open_full (in /usr/local/lib/libgmodule-2.0.so.0.7000.4)
==81101==    by 0x2029A6: ??? (in /usr/local/bin/gdk-pixbuf-query-loaders)
==81101==    by 0x20289D: ??? (in /usr/local/bin/gdk-pixbuf-query-loaders)
==81101==    by 0x20246F: ??? (in /usr/local/bin/gdk-pixbuf-query-loaders)
==81101==    by 0x482AFFF: ???
==81101== Your program just tried to execute an instruction that Valgrind
==81101== did not recognise.  There are two possible reasons for this.
==81101== 1. Your program has a bug and erroneously jumped to a non-code
==81101==    location.  If you are running Memcheck and you just saw a
==81101==    warning about a bad jump, it's probably your program's fault.
==81101== 2. The instruction is legitimate but Valgrind doesn't handle it,
==81101==    i.e. it's Valgrind's fault.  If you think this is the case or
==81101==    you are not sure, please let us know and we'll try to fix it.
==81101== Either way, Valgrind will now raise a SIGILL signal which will
==81101== probably kill your program.
==81101==
==81101== Process terminating with default action of signal 4 (SIGILL): dumping core
==81101==  Illegal opcode at address 0x52BF3A2
==81101==    at 0x52BF3A2: ??? (in /usr/local/lib/libhwy.so.0.16.0)
==81101==    by 0x400D47C: ??? (in /libexec/ld-elf.so.1)
==81101==    by 0x40120A3: ??? (in /libexec/ld-elf.so.1)
==81101==    by 0x400E79A: ??? (in /libexec/ld-elf.so.1)
==81101==    by 0x49F6B3B: g_module_open_full (in /usr/local/lib/libgmodule-2.0.so.0.7000.4)
==81101==    by 0x2029A6: ??? (in /usr/local/bin/gdk-pixbuf-query-loaders)
==81101==    by 0x20289D: ??? (in /usr/local/bin/gdk-pixbuf-query-loaders)
==81101==    by 0x20246F: ??? (in /usr/local/bin/gdk-pixbuf-query-loaders)
==81101==    by 0x482AFFF: ???
==81101==
==81101== HEAP SUMMARY:
==81101==     in use at exit: 81,561 bytes in 639 blocks
==81101==   total heap usage: 1,079 allocs, 440 frees, 259,279 bytes allocated
==81101==
==81101== LEAK SUMMARY:
==81101==    definitely lost: 11,829 bytes in 19 blocks
==81101==    indirectly lost: 275 bytes in 14 blocks
==81101==      possibly lost: 15,114 bytes in 91 blocks
==81101==    still reachable: 54,343 bytes in 515 blocks
==81101==                       of which reachable via heuristic:
==81101==                         newarray           : 1,536 bytes in 16 blocks
==81101==         suppressed: 0 bytes in 0 blocks
==81101== Rerun with --leak-check=full to see details of leaked memory
==81101==
==81101== For lists of detected and suppressed errors, rerun with: -s
==81101== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Illegal instruction
```

gdk-pixbuf-query-loaders run fine on Xeon Bronze 3104 with `-O2 -march=skylake-avx512`.

**Comment by VVD** [comment]
Core 2 Duo E7200:
```
$ cpuid
 eax in    eax      ebx      ecx      edx
00000000 0000000a 756e6547 6c65746e 49656e69
00000001 00010676 01020800 0008e39d bfebfbff
00000002 05b0b101 005657f0 00000000 2cb43048
00000003 00000000 00000000 00000000 00000000
00000004 04000121 01c0003f 0000003f 00000001
00000005 00000040 00000040 00000003 00022220
00000006 00000001 00000002 00000001 00000000
00000007 00000000 00000000 00000000 00000000
00000008 00000400 00000000 00000000 00000000
00000009 00000000 00000000 00000000 00000000
0000000a 07280202 00000000 00000000 00000503
80000000 80000008 00000000 00000000 00000000
80000001 00000000 00000000 00000001 20100800
80000002 65746e49 2952286c 726f4320 4d542865
80000003 44203229 43206f75 20205550 45202020
80000004 30303237 20402020 33352e32 007a4847
80000005 00000000 00000000 00000000 00000000
80000006 00000000 00000000 0c006040 00000000
80000007 00000000 00000000 00000000 00000000
80000008 00003024 00000000 00000000 00000000

Vendor ID: "GenuineIntel"; CPUID level 10

Intel-specific functions:
Version 00010676:
Type 0 - Original OEM
Family 6 - Pentium Pro
Model 23 - Intel Core2 Extreme or Xeon processor, 45nm
Stepping 6
Reserved 0

Extended brand string: "Intel(R) Core(TM)2 Duo CPU     E7200  @ 2.53GHz"
CLFLUSH instruction cache line size: 8
Initial APIC ID: 1
Hyper threading siblings: 2

Feature flags set 1 (CPUID.01H:EDX): bfebfbff:
FPU    Floating Point Unit
VME    Virtual 8086 Mode Enhancements
DE     Debugging Extensions
PSE    Page Size Extensions
TSC    Time Stamp Counter
MSR    Model Specific Registers
PAE    Physical Address Extension
MCE    Machine Check Exception
CX8    COMPXCHG8B Instruction
APIC   On-chip Advanced Programmable Interrupt Controller present and enabled
SEP    Fast System Call
MTRR   Memory Type Range Registers
PGE    PTE Global Flag
MCA    Machine Check Architecture
CMOV   Conditional Move and Compare Instructions
FGPAT  Page Attribute Table
PSE-36 36-bit Page Size Extension
CLFSH  CFLUSH instruction
DS     Debug store
ACPI   Thermal Monitor and Clock Ctrl
MMX    MMX instruction set
FXSR   Fast FP/MMX Streaming SIMD Extensions save/restore
SSE    Streaming SIMD Extensions instruction set
SSE2   SSE2 extensions
SS     Self Snoop
HT     Hyper Threading
TM     Thermal monitor
31     Pending Break Enable

Feature flags set 2 (CPUID.01H:ECX): 0008e39d:
SSE3     SSE3 extensions
DTES64   64-bit debug store
MONITOR  MONITOR/MWAIT instructions
DS-CPL   CPL Qualified Debug Store
EST      Enhanced Intel SpeedStep Technology
TM2      Thermal Monitor 2
SSSE3    Supplemental Streaming SIMD Extension 3
CX16     CMPXCHG16B
xTPR     Send Task Priority messages
PDCM     Perfmon and debug capability
SSE4.1   Streaming SIMD Extension 4.1

Extended feature flags set 1 (CPUID.80000001H:EDX): 20100800
SYSCALL   SYSCALL/SYSRET instructions
XD-bit    Execution Disable bit
EM64T     Intel Extended Memory 64 Technology

Extended feature flags set 2 (CPUID.80000001H:ECX): 00000001
LAHF      LAHF/SAHF available in IA-32e mode

Old-styled TLB and cache info:
b1: Instruction TLB: 2MB Pages (8 entries) or 4MB pages (4 entries), 4-way set associative
b0: Instruction TLB: 4-KB Pages, 4-way set associative, 128 entries
05: Data TLB: 4MB pages, 4-way set assoc, 32 entries
f0: 64-byte prefetching
57: Data TLB: 4KB pages, 4-way set associative, 16 entries
56: Data TLB: 4MB pages, 4-way set associative, 16 entries
48: 2nd-level cache: 3MB, 12-way set associative, 64-byte line size, unified on die
30: 1st-level instruction cache: 32-KB, 8-way set associative, 64-byte line size
b4: Data TLB: 4-KB Pages, 4-way set associative, 256 entries
2c: 1st-level data cache: 32-KB, 8-way set associative, 64-byte line size

Processor serial: 0001-0676-0000-0000-0000-0000

Deterministic Cache Parameters:
index=0: eax=04000121 ebx=01c0003f ecx=0000003f edx=00000001
> Data cache, level 1, self initializing
> 64 sets, 8 ways, 1 partitions, line size 64
> full size 32768 bytes
> NB this package has up to 2 threads
index=1: eax=04000122 ebx=01c0003f ecx=0000003f edx=00000001
> Instruction cache, level 1, self initializing
> 64 sets, 8 ways, 1 partitions, line size 64
> full size 32768 bytes
index=2: eax=04004143 ebx=02c0003f ecx=00000fff edx=00000001
> Unified cache, level 2, self initializing
> 4096 sets, 12 ways, 1 partitions, line size 64
> full size 3145728 bytes
> shared between up to 2 thread
```

**Comment by VVD** [comment]
Core 2 Duo E6550:
```
$ cpuid
 eax in    eax      ebx      ecx      edx
00000000 0000000a 756e6547 6c65746e 49656e69
00000001 000006fb 00020800 0000e3fd bfebfbff
00000002 05b0b101 005657f0 00000000 2cb43049
00000003 00000000 00000000 00000000 00000000
00000004 04000121 01c0003f 0000003f 00000001
00000005 00000040 00000040 00000003 00000220
00000006 00000001 00000002 00000001 00000000
00000007 00000000 00000000 00000000 00000000
00000008 00000400 00000000 00000000 00000000
00000009 00000000 00000000 00000000 00000000
0000000a 07280202 00000000 00000000 00000503
80000000 80000008 00000000 00000000 00000000
80000001 00000000 00000000 00000001 20100800
80000002 65746e49 2952286c 726f4320 4d542865
80000003 44203229 43206f75 20205550 45202020
80000004 30353536 20402020 33332e32 007a4847
80000005 00000000 00000000 00000000 00000000
80000006 00000000 00000000 10008040 00000000
80000007 00000000 00000000 00000000 00000000
80000008 00003024 00000000 00000000 00000000

Vendor ID: "GenuineIntel"; CPUID level 10

Intel-specific functions:
Version 000006fb:
Type 0 - Original OEM
Family 6 - Pentium Pro
Model 15 - Intel Core2 family processor, 65nm
Stepping 11
Reserved 0

Extended brand string: "Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz"
CLFLUSH instruction cache line size: 8
Hyper threading siblings: 2

Feature flags set 1 (CPUID.01H:EDX): bfebfbff:
FPU    Floating Point Unit
VME    Virtual 8086 Mode Enhancements
DE     Debugging Extensions
PSE    Page Size Extensions
TSC    Time Stamp Counter
MSR    Model Specific Registers
PAE    Physical Address Extension
MCE    Machine Check Exception
CX8    COMPXCHG8B Instruction
APIC   On-chip Advanced Programmable Interrupt Controller present and enabled
SEP    Fast System Call
MTRR   Memory Type Range Registers
PGE    PTE Global Flag
MCA    Machine Check Architecture
CMOV   Conditional Move and Compare Instructions
FGPAT  Page Attribute Table
PSE-36 36-bit Page Size Extension
CLFSH  CFLUSH instruction
DS     Debug store
ACPI   Thermal Monitor and Clock Ctrl
MMX    MMX instruction set
FXSR   Fast FP/MMX Streaming SIMD Extensions save/restore
SSE    Streaming SIMD Extensions instruction set
SSE2   SSE2 extensions
SS     Self Snoop
HT     Hyper Threading
TM     Thermal monitor
31     Pending Break Enable

Feature flags set 2 (CPUID.01H:ECX): 0000e3fd:
SSE3     SSE3 extensions
DTES64   64-bit debug store
MONITOR  MONITOR/MWAIT instructions
DS-CPL   CPL Qualified Debug Store
VMX      Virtual Machine Extensions
SMX      Safer Mode Extension
EST      Enhanced Intel SpeedStep Technology
TM2      Thermal Monitor 2
SSSE3    Supplemental Streaming SIMD Extension 3
CX16     CMPXCHG16B
xTPR     Send Task Priority messages
PDCM     Perfmon and debug capability

Extended feature flags set 1 (CPUID.80000001H:EDX): 20100800
SYSCALL   SYSCALL/SYSRET instructions
XD-bit    Execution Disable bit
EM64T     Intel Extended Memory 64 Technology

Extended feature flags set 2 (CPUID.80000001H:ECX): 00000001
LAHF      LAHF/SAHF available in IA-32e mode

Old-styled TLB and cache info:
b1: Instruction TLB: 2MB Pages (8 entries) or 4MB pages (4 entries), 4-way set associative
b0: Instruction TLB: 4-KB Pages, 4-way set associative, 128 entries
05: Data TLB: 4MB pages, 4-way set assoc, 32 entries
f0: 64-byte prefetching
57: Data TLB: 4KB pages, 4-way set associative, 16 entries
56: Data TLB: 4MB pages, 4-way set associative, 16 entries
49: 3rd-level cache: 4MB, 16-way set associative, 64-byte line size (Intel Xeon MP, Family 0Fh, Model 06h
OR 2nd-level cache: 4MB, 16-way set associative, 64-byte line size
30: 1st-level instruction cache: 32-KB, 8-way set associative, 64-byte line size
b4: Data TLB: 4-KB Pages, 4-way set associative, 256 entries
2c: 1st-level data cache: 32-KB, 8-way set associative, 64-byte line size

Processor serial: 0000-06FB-0000-0000-0000-0000

Deterministic Cache Parameters:
index=0: eax=04000121 ebx=01c0003f ecx=0000003f edx=00000001
> Data cache, level 1, self initializing
> 64 sets, 8 ways, 1 partitions, line size 64
> full size 32768 bytes
> NB this package has up to 2 threads
index=1: eax=04000122 ebx=01c0003f ecx=0000003f edx=00000001
> Instruction cache, level 1, self initializing
> 64 sets, 8 ways, 1 partitions, line size 64
> full size 32768 bytes
index=2: eax=04004143 ebx=03c0003f ecx=00000fff edx=00000001
> Unified cache, level 2, self initializing
> 4096 sets, 16 ways, 1 partitions, line size 64
> full size 4194304 bytes
> shared between up to 2 threads
```

**Comment by VVD** [comment]
Fast test:
```
$ cat testSSE.c
#include <stdio.h>

int main()
{
#if defined(__SSE4_1__)
printf("YES\n");
#else
printf("NO\n");
#endif
return 0;
}
$ clang -O2 -march=core2 -o testSSE testSSE.c
$ ./testSSE
NO
```

**Comment by VVD** [comment]
Dependency "tree": highway-0.16.0 => libjxl-0.6.1 => ImageMagick7-7.1.0.19.

**Comment by jan-wassenberg** [comment]
Hi @VVD , thanks for reporting this with such extensive information. The valgrind report is a great idea, that shows the problem is actually RDTSCP (used for timing) instead of SIMD/SSE4. I've prepared a patch which should fix this.

**Comment by jan-wassenberg** [comment]
@VVD Great to hear, thanks for confirming! At this point, no need for CPUID as long as all the tests pass.

**Comment by novomesk** [comment]
@jan-wassenberg 
Do you think the problem reported in https://bugs.gentoo.org/841413 is the same?
Eric, who reported the problem, is using Core2Duo too.

**Comment by jan-wassenberg** [comment]
@novomesk yes, that seems likely. Unfortunately the fix for this came shortly after the latest release (0.16). I'm happy to do another release soon, latest by next week.
